version = 1

test_patterns = [
  "**/*Test*.java",
  "**/__tests__/**",
  "**/*.spec.ts",
  "**/*.spec.js",
  "**/*.test.ts",
  "**/*.test.js",
  "**/test_*.py"
]

exclude_patterns = [
  "node_modules",
  "bower_components",
  "out",
  "bin",
  "build",
  "dist",
  "venv"
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"