# DeepSource configuration file
# Learn how to configure: https://docs.deepsource.com/docs/configuration
version = 1
exclude_patterns = ["node_modules", "bower_components", "out", "bin", "build", "dist", "venv"]
test_patterns = ["**/*Test*.java", "**/__tests__/**", "**/*.spec.ts", "**/*.spec.js", "**/*.test.ts", "**/*.test.js", "**/test_*.py"]

[[analyzers]]
  name = "java"
  enabled = true

[[analyzers]]
  name = "javascript"
  enabled = true

[[analyzers]]
  name = "python"
  enabled = true
